import { Typography, Box, useMediaQuery } from "@mui/material";
import Head from "next/head";
import SwipeableEdgeDrawerDesktop from "@/components/SwipeableEdgeDrawerDesktop";
import SwipeableEdgeDrawerMobile from "@/components/SwipeableEdgeDrawerMobile";
import SwipeableEdgeDrawer from "@/components/SwipeableEdgeDrawer";
import HeroGif from "@/components/HeroGif";
import { useState, useCallback } from "react";
import IntroScreen from "@/components/IntroScreen";
import { theme } from "@/styles/theme";
import AboutMeMobile from "@/components/AboutMeMobile";
import AboutMeDesktop from "@/components/AboutMeDesktop";
import CareerTimelineDesktop from "@/components/CareerTimelineDesktop";
import CareerTimelineMobile from "@/components/CareerTimelineMobile";
import ProjectsDesktop from "@/components/ProjectsDesktop";
import ProjectsMobile from "@/components/ProjectsMobile";
import Contact from "@/components/Contact";
import ContactDesktop from "@/components/ContactDesktop";
import ContactMobile from "@/components/ContactMobile";
import Cookies from "js-cookie";

const drawerWidth = 240;

export default function Home() {
  const [paused, setPaused] = useState(null);

  const handleOpen = (open) => {
    setPaused(open);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/headphones.png" />
      </Head>
      <IntroScreen />
      <Box display="flex" overflow={"hidden"} height={"100%"} width={"100%"}>
        {/* Mobile */}
        <Box sx={{ display: { xs: "flex", sm: "none" } }}>
          <SwipeableEdgeDrawer
            anchor="top"
            label="About Me"
            drawerWidth="100%"
            transformButton="translateX(-50%)"
            handleOpen={handleOpen}
          >
            <AboutMeMobile />
          </SwipeableEdgeDrawer>
        </Box>
        {/* Desktop */}
        <Box sx={{ display: { xs: "none", sm: "flex" } }}>
          <SwipeableEdgeDrawer
            anchor="top"
            label="About Me"
            drawerWidth="100%"
            transformButton="translateX(-50%)"
            handleOpen={handleOpen}
          >
            <AboutMeDesktop />
          </SwipeableEdgeDrawer>
        </Box>
        {/* under md */}
        <SwipeableEdgeDrawerMobile
          anchor="right"
          label="Projects"
          drawerWidth={drawerWidth}
          transformButton={"translateY(-50%) rotate(90deg)"}
          handleOpen={handleOpen}
          sx={{ display: { xs: "block", sm: "none" } }}
        >
          <ProjectsMobile />
        </SwipeableEdgeDrawerMobile>
        {/* over md */}
        <SwipeableEdgeDrawerDesktop
          anchor="right"
          label="Projects"
          drawerWidth={drawerWidth}
          transformButton={"translateY(-50%) translateX(-100px)"}
          handleOpen={handleOpen}
          sx={{ display: { xs: "none", sm: "block" } }}
        >
          <ProjectsDesktop />
        </SwipeableEdgeDrawerDesktop>
        {/* Mobile */}
        <Box sx={{ display: { xs: "block", sm: "none" } }}>
          <SwipeableEdgeDrawer
            anchor="bottom"
            label="Contact Me"
            drawerWidth="100%"
            transformButton="translateX(-50%)"
            handleOpen={handleOpen}
          >
            <ContactMobile />
          </SwipeableEdgeDrawer>
        </Box>
        {/* Desktop */}
        <Box sx={{ display: { xs: "none", sm: "block" } }}>
          <SwipeableEdgeDrawer
            anchor="bottom"
            label="Contact Me"
            drawerWidth="100%"
            transformButton="translateX(-50%)"
            handleOpen={handleOpen}
          >
            <ContactDesktop />
          </SwipeableEdgeDrawer>
        </Box>
        {/* under md */}
        <SwipeableEdgeDrawerMobile
          anchor="left"
          label="Career Timeline"
          drawerWidth={drawerWidth}
          transformButton={"translateY(-50%) translateX(-100px) rotate(-90deg)"}
          handleOpen={handleOpen}
          sx={{ display: { xs: "block", sm: "none" } }}
        >
          <CareerTimelineMobile />
        </SwipeableEdgeDrawerMobile>
        {/* md and over */}
        <SwipeableEdgeDrawerDesktop
          anchor="left"
          label="Career Timeline"
          drawerWidth={drawerWidth}
          transformButton={"translateY(-50%)"}
          handleOpen={handleOpen}
          sx={{ display: { xs: "none", sm: "block" } }}
        >
          <CareerTimelineDesktop />
        </SwipeableEdgeDrawerDesktop>
        <Box
          position={"fixed"}
          display={"flex"}
          justifyContent={"center"}
          alignItems={"center"}
          // paddingY="300px"
          // sx={{ paddingY: { xs: "300px", sm: "150px", md: "200px" } }}
          height={"100%"}
          width={"100%"}
          overflow="hidden"
        >
          <HeroGif paused={paused} />
        </Box>
      </Box>
    </>
  );
}
