import { Typography, Box, useMediaQuery } from "@mui/material";
import Head from "next/head";
import SwipeableEdgeDrawer from "@/components/SwipeableEdgeDrawer";
import HeroGif from "@/components/HeroGif";
import { useState, useCallback } from "react";
import IntroScreen from "@/components/IntroScreen";
import { theme } from "@/styles/theme";

const drawerWidth = 240;

export default function Home() {
  const [paused, setPaused] = useState(null);
  const isMobile = useMediaQuery(
    `(max-width: ${theme.breakpoints.values.md}px`
  );

  const careerTransform = isMobile
    ? "translateY(-50%) translateX(-100px) rotate(-90deg)"
    : "translateY(-50%)";

  const projectsTransform = isMobile
    ? "translateY(-50%) rotate(90deg)"
    : "translateY(-50%) translateX(-100px)";

  const handleOpen = (open) => {
    setPaused(open);
  };

  // console.log(paused);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/headphones.png" />
      </Head>
      <IntroScreen />
      <Box display="flex" overflow={"hidden"} height={"100%"} width={"100%"}>
        <SwipeableEdgeDrawer
          anchor="top"
          label="About Me"
          drawerWidth="100%"
          transform="translateX(-50%)"
          handleOpen={handleOpen}
        >
          <Typography>About Me</Typography>
        </SwipeableEdgeDrawer>
        <SwipeableEdgeDrawer
          anchor="right"
          label="Projects"
          drawerWidth={drawerWidth}
          transform={projectsTransform}
          handleOpen={handleOpen}
        >
          <Typography width={"100%"}>Projects</Typography>
        </SwipeableEdgeDrawer>
        <SwipeableEdgeDrawer
          anchor="bottom"
          label="Contact Me"
          drawerWidth="100%"
          transform="translateX(-50%)"
          handleOpen={handleOpen}
        >
          <Typography>Contact Me</Typography>
        </SwipeableEdgeDrawer>
        <SwipeableEdgeDrawer
          anchor="left"
          label="Career Timeline"
          drawerWidth={drawerWidth}
          transform={careerTransform}
          handleOpen={handleOpen}
        >
          <Typography justify="center" width={"100%"}>
            Career Timeline
          </Typography>
        </SwipeableEdgeDrawer>
        <HeroGif paused={paused} />
      </Box>
    </>
  );
}
